metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_factor = 1
compression_level = 2
metadata_auto_snapshot_interval = "6h"

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "s3:3901"
rpc_secret = "bfa9c4b960786a1319eacb3fc8211ae00f901200e869cb43329e37d5e2a4d83b"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "0.0.0.0:3902"
root_domain = ".web.garage.localhost"

[admin]
api_bind_addr = "0.0.0.0:3903"
admin_token = "c63e955f49b3d0df092af171a6c20938e7eefa0d3473e592b1ad4dee3a904fb6"
metrics_token = "09221ae2692b4de3174dc722e94b99654d16dc16ba6b02bce2fc8c9f059207af"
